export const components  = [
    {
        'ProductID': 1,
        'comp': 'Kobold Coil Connector',
        'sn': 'N/A',
        'length': 0.25,
        'od': 85.5,
        'id': 60.3,
        'descrip': 'Coil Connector with High Flow Thread.',
    },
    {
        'ProductID': 2,
        'comp': 'Hydraulic Disconnect',
        'sn': 'N/A',
        'length': 0.42,
        'od': 85.54,
        'id': 31.73,
        'descrip': 'Hydraulic Disconnect set to shear @ 44.8 MPa.',
    },
    {
        'ProductID': 3,
        'comp': 'Guide Sub',
        'sn': '28',
        'length': 0.74,
        'od': 85.65,
        'id': 43.94,
        'descrip': 'High Flow Guide Sub battery on @ March 8 14:54.',
    },
    {
        'ProductID': 4,
        'comp': 'Jet Sub',
        'sn': 'N/A',
        'length': 0.15,
        'od': 85.8,
        'id': 43.26,
        'descrip': 'High Flow Jet Sub with 4-3/16" Jets.',
    },
    {
        'ProductID': 5,
        'comp': 'By Pass Valve',
        'sn': 'N/A',
        'length': 0.96,
        'od': 85.8,
        'id': '',
        'descrip': 'Blank Bypass Valve Single Seal Stroke Length 0.24m.',
    },
    {
        'ProductID': 6,
        'comp': 'Sandhawk G5',
        'sn': 'N/A',
        'length': 2.05,
        'od': 116.5,
        'id': 25.4,
        'descrip': 'Sandhawk G5 Frac Tool.',
    },
    {
        'ProductID': 7,
        'comp': 'Toe Sub',
        'sn': 'TS-0023',
        'length': 4.5,
        'od': 94.5,
        'id': 90.75,
        'descrip': 'Pressurized Toe Sub.',
    }
]
